- name: prerequisites
  apt:
    name: python3-yaml
    state: present

- name: Install helm if not exists
  unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm

- name: Copier le chart Helm sur la VM
  copy:
    src: "{{ playbook_dir }}/charts/app/"  
    dest: "/tmp/app/"                     
    owner: root
    group: root
    mode: '0755'

- name: Deploy application
  kubernetes.core.helm:
    name: example-app
    chart_ref: "{{ playbook_dir }}/charts/app"
    release_namespace: example-app
    create_namespace: true