- name: apt update
  apt:
    update-cache: yes
    cache_valid_time: 3600

- name: Check if certificate already exists
  stat:
    path: /etc/ssl/certificate.pem
  register: __certificate_already_created

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/certificate.key
  when: not __certificate_already_created.stat.exists

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/certificate.pem
    privatekey_path: /etc/ssl/certificate.key
    provider: selfsigned
  when: not __certificate_already_created.stat.exists

- name: install haproxy
  apt:
    name: haproxy
    state: present

- name: Install haproxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: reload_haproxy

- name: start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
