- name: apt update
  apt:
    update-cache: yes
    cache_valid_time: 3600

- name: Check if certificate already exists
  stat:
    path: /etc/ssl/cert.pem
  register: __certificate_already_created

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: /etc/ssl/cert.key
  when: not __certificate_already_created.stat.exists

- name: Générer une CSR
  community.crypto.openssl_csr:
    path: "/etc/ssl/cert.csr"
    privatekey_path: "/etc/ssl/cert.key"
    common_name: "toto.com"
    subject_alt_name:
      - "DNS:toto.com"

- name: Générer un certificat auto-signé
  community.crypto.x509_certificate:
    path: "/etc/ssl/cert.pem"
    privatekey_path: "/etc/ssl/cert.key"
    csr_path: "/etc/ssl/cert.csr"
    provider: selfsigned

- name: Concaténer clé + cert pour HAProxy
  ansible.builtin.shell: cat /etc/ssl/cert.key /etc/ssl/cert.pem > /etc/ssl/haproxy.pem
  args:
    creates: /etc/ssl/haproxy.pem

- name: install haproxy
  apt:
    name: haproxy
    state: present

- name: Install haproxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: reload_haproxy

- name: start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
