- name: load balancer
  hosts: k8s_lb
  become: true
  roles:
  - haproxy

- name: kubernetes
  hosts: k8s_masters,k8s_workers
  become: true
  serial:
  - 1
  - 1
  - 1
  - "100%"
  roles:
  - kubernetes

- name: ingress controller
  hosts: kubm1
  become: true
  roles:
  - addons

- name: applications
  hosts: kubm1
  become: true
  roles: applications
  tags: applications