- name: load balancer
  hosts: k8s_lb
  become: true
  roles: 
    - role: haproxy
      tags: haproxy

- name: kubernetes
  hosts: k8s_masters,k8s_workers
  become: true
  serial:
  - 1
  - 1
  - 1
  - "100%"
  roles: 
    - role: kubernetes
      tags: kubernetes

- name: ingress controller
  hosts: kubm1
  become: true
  roles: 
    - role: addons
      tags: addons

- name: applications
  hosts: kubm1
  become: true
  roles: 
    - role: applications
      tags: applications
